base_config: ../default.yaml

baselines:
  ppo_resnet18_lstm_ft:
    learning_rate: 3.0e-5
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    total_timesteps: 1_000_000
    visual_dim: 128
    unfreeze_layers: ["layer4"]
    lstm_hidden_size: 128
    n_lstm_layers: 1
    policy_hidden_sizes: [128]
    value_hidden_sizes: [128]
    tb_log_name: resnet18_lstm_ppo_ft_lr3e5_layer4_lstm128
    save_path: trained_models/ppo_resnet18_lstm_ft_lr3e5_layer4_lstm128
