"""
Training script for the RL controller.

Trains the policy in latent space using imagined rollouts generated by the
dynamics model (following the Dreamer-style training loop).
"""


def train(config: dict):
    raise NotImplementedError


if __name__ == "__main__":
    import sys

    from utils.config import load_config

    config = load_config(sys.argv[1])
    train(config)
