"""
Training script for the RL controller.

Trains the policy in latent space using imagined rollouts generated by the
dynamics model (following the Dreamer-style training loop).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter

from models.controller.policy import Policy, ValueFunction
from models.dynamics.transformer import LatentDynamicsModel, RewardPredictor
from models.encoder.vae import VAE
from sim.env import RoboticArmEnv


class _LatentReplayBuffer:
    def __init__(self, capacity: int, latent_dim: int, action_dim: int):
        self.latents = np.zeros((capacity, latent_dim), dtype=np.float32)
        self.actions = np.zeros((capacity, action_dim), dtype=np.float32)
        self.rewards = np.zeros(capacity, dtype=np.float32)
        self.dones = np.zeros(capacity, dtype=bool)
        self.ptr = 0
        self.size = 0
        self.capacity = capacity

    def add(self, z, a, r, done):
        self.latents[self.ptr] = z
        self.actions[self.ptr] = a
        self.rewards[self.ptr] = r
        self.dones[self.ptr] = done
        self.ptr = (self.ptr + 1) % self.capacity
        self.size = min(self.size + 1, self.capacity)

    def sample_starting_states(self, batch_size: int) -> torch.Tensor:
        valid = np.where(~self.dones[: self.size])[0]
        idx = np.random.choice(valid, size=batch_size, replace=True)
        return torch.from_numpy(self.latents[idx])

    def sample_transitions(self, batch_size: int):
        idx = np.random.randint(0, self.size, size=batch_size)
        return (
            torch.from_numpy(self.latents[idx]),
            torch.from_numpy(self.rewards[idx]),
        )


def _compute_lambda_returns(
    rewards: torch.Tensor,
    values: torch.Tensor,
    gamma: float,
    lam: float,
) -> torch.Tensor:
    """
    rewards: (B, H)    — imagined rewards r_0..r_{H-1}
    values:  (B, H+1)  — critic values V_0..V_H (V_H is the bootstrap)
    Returns: lambda_returns (B, H)
    """
    B, H = rewards.shape
    lambda_rets = torch.zeros_like(rewards)
    last = values[:, -1]
    for t in reversed(range(H)):
        last = rewards[:, t] + gamma * ((1 - lam) * values[:, t + 1] + lam * last)
        lambda_rets[:, t] = last
    return lambda_rets


def _collect_real_data(env, vae, policy, replay, device, n_episodes: int):
    vae.eval()
    policy.eval()
    with torch.no_grad():
        for _ in range(n_episodes):
            obs, _ = env.reset()
            done = False
            while not done:
                img = (
                    torch.from_numpy(obs["image"])
                    .permute(2, 0, 1)
                    .float()
                    .unsqueeze(0)
                    / 255.0
                ).to(device)
                z = vae.encode(img).squeeze(0)

                if replay.size < 1000:
                    action = env.action_space.sample()
                else:
                    action, _, _ = policy.sample(z.unsqueeze(0))
                    action = action.squeeze(0).cpu().numpy()

                obs, reward, terminated, truncated, _ = env.step(action)
                done = terminated or truncated
                replay.add(
                    z.cpu().numpy(),
                    action.astype(np.float32),
                    float(reward),
                    done,
                )
    policy.train()


def train(config: dict):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    enc_cfg = config["encoder"]
    dyn_cfg = config["dynamics"]
    ctrl_cfg = config["controller"]

    latent_dim = enc_cfg["latent_dim"]
    gamma = ctrl_cfg["gamma"]
    H = ctrl_cfg["imagination_horizon"]
    lam = 0.95
    batch_size = 64
    total_updates = 5000

    # Load frozen models
    vae = VAE(latent_dim).to(device)
    vae.load_state_dict(torch.load("checkpoints/encoder.pt", map_location=device))
    vae.eval()
    for p in vae.parameters():
        p.requires_grad = False

    env = RoboticArmEnv(config)
    action_dim = env.action_space.shape[0]

    dynamics = LatentDynamicsModel(
        latent_dim=latent_dim,
        action_dim=action_dim,
        d_model=dyn_cfg["d_model"],
        nhead=dyn_cfg["nhead"],
        num_layers=dyn_cfg["num_layers"],
        max_seq_len=dyn_cfg["max_seq_len"],
    ).to(device)
    dynamics.load_state_dict(
        torch.load("checkpoints/dynamics.pt", map_location=device)
    )
    dynamics.eval()
    for p in dynamics.parameters():
        p.requires_grad = False

    reward_pred = RewardPredictor(latent_dim).to(device)
    if os.path.exists("checkpoints/reward_predictor.pt"):
        reward_pred.load_state_dict(
            torch.load("checkpoints/reward_predictor.pt", map_location=device)
        )
    reward_opt = torch.optim.Adam(reward_pred.parameters(), lr=1e-3)

    # Trainable actor-critic
    policy = Policy(latent_dim, action_dim, ctrl_cfg["hidden_dim"]).to(device)
    value_fn = ValueFunction(latent_dim, ctrl_cfg["hidden_dim"]).to(device)

    actor_opt = torch.optim.Adam(policy.parameters(), lr=ctrl_cfg["learning_rate"])
    critic_opt = torch.optim.Adam(value_fn.parameters(), lr=ctrl_cfg["learning_rate"])

    replay = _LatentReplayBuffer(100_000, latent_dim, action_dim)

    log_dir = os.path.join(config["evaluation"]["log_dir"], "controller")
    writer = SummaryWriter(log_dir=log_dir)

    # Warm-start replay buffer
    print("Collecting initial data...")
    _collect_real_data(env, vae, policy, replay, device, n_episodes=50)
    print(f"Replay buffer has {replay.size} transitions")

    for update_step in range(total_updates):
        # Periodic real-env data collection
        if update_step > 0 and update_step % 10 == 0:
            _collect_real_data(env, vae, policy, replay, device, n_episodes=5)

        # ---- Reward predictor update (supervised on real transitions) ----
        rp_z, rp_r = replay.sample_transitions(batch_size)
        rp_z, rp_r = rp_z.to(device), rp_r.to(device)
        reward_opt.zero_grad()
        rp_loss = F.mse_loss(reward_pred(rp_z).squeeze(-1), rp_r)
        rp_loss.backward()
        reward_opt.step()

        # ---- Imagination rollout ----
        z0 = replay.sample_starting_states(batch_size).to(device)  # (B, 128)

        ctx_z = z0.unsqueeze(1)                              # (B, 1, latent_dim)
        ctx_a = torch.zeros(batch_size, 1, action_dim, device=device)

        z_t = z0
        imagined_z: list = []
        imagined_r: list = []

        policy.train()
        for _ in range(H):
            action, _, _ = policy.sample(z_t)               # (B, action_dim), reparameterized
            r_t = reward_pred(z_t)                           # (B, 1)

            ctx_z = torch.cat([ctx_z, z_t.unsqueeze(1)], dim=1)
            ctx_a = torch.cat([ctx_a, action.unsqueeze(1)], dim=1)

            z_next = dynamics.step(ctx_z, ctx_a)            # (B, latent_dim)

            imagined_z.append(z_t)
            imagined_r.append(r_t)
            z_t = z_next

        z_traj = torch.stack(imagined_z, dim=1)             # (B, H, latent_dim)
        r_traj = torch.cat(imagined_r, dim=1)               # (B, H)

        # Value targets: detached from critic params so critic.step() can't corrupt
        # the actor's computation graph. Actor grads flow through r_traj only.
        with torch.no_grad():
            v_all = value_fn(z_traj).squeeze(-1)            # (B, H)
            v_boot = value_fn(z_t).squeeze(-1)              # (B,)
        values = torch.cat([v_all, v_boot.unsqueeze(1)], dim=1)  # (B, H+1)

        # lambda_rets: grad path is r_traj → imagined z/actions → policy.sample
        lambda_rets = _compute_lambda_returns(r_traj, values, gamma, lam)

        # Critic update
        critic_opt.zero_grad()
        v_pred = value_fn(z_traj.detach()).squeeze(-1)       # (B, H)
        critic_loss = F.mse_loss(v_pred, lambda_rets.detach())
        critic_loss.backward()
        critic_opt.step()

        # Actor update
        actor_opt.zero_grad()
        actor_loss = -lambda_rets.mean()
        actor_loss.backward()
        nn.utils.clip_grad_norm_(policy.parameters(), max_norm=100.0)
        actor_opt.step()

        writer.add_scalar("controller/actor_loss", actor_loss.item(), update_step)
        writer.add_scalar("controller/critic_loss", critic_loss.item(), update_step)
        writer.add_scalar(
            "controller/mean_imagined_reward", r_traj.mean().item(), update_step
        )
        writer.add_scalar("controller/reward_pred_loss", rp_loss.item(), update_step)

        if (update_step + 1) % 100 == 0:
            print(
                f"Step {update_step+1}/{total_updates} | "
                f"actor={actor_loss.item():.4f} | "
                f"critic={critic_loss.item():.4f} | "
                f"imag_r={r_traj.mean().item():.4f} | "
                f"rp_loss={rp_loss.item():.4f}"
            )

    env.close()
    os.makedirs("checkpoints", exist_ok=True)
    torch.save(policy.state_dict(), "checkpoints/policy.pt")
    writer.close()
    print("Policy saved to checkpoints/policy.pt")


if __name__ == "__main__":
    import sys

    import yaml

    with open(sys.argv[1]) as f:
        config = yaml.safe_load(f)
    train(config)
